### ISSUE TITLE
Add optional Serde support

### ISSUE THREAD

**Issue by dtolnay** [tylerreisinger/rust-float-duration#1]
I would love to be able to serialize and deserialize `FloatDuration`. I imagine it would be represented by Serde's f64 type.

**Comment by tylerreisinger** [comment]
Implemented serde support in [`bf7cd67`](https://github.com/tylerreisinger/rust-float-duration/commit/bf7cd67314ff0034f65e7688585d70f38f1d10d0). FloatDuration should now serialize to a single f64.
